spring:
  application:
    name: Api-Gateway
 data:
    
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: aadhaar-service
          uri: lb://order-service
          predicates:
            - Path=/order/fetchdata/**
          filters:
            - StripPrefix=2
