spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://order-service
          predicates:
            - Path=/order/fetchdata/{id}
          filters:
            - StripPrefix=1
