spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/fetchdata/**
          filters:
            - StripPrefix=1
